_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

min_epochs: 1  # prevents early stopping
max_epochs: 100

gradient_clip_val: 0.5

accelerator: gpu
devices: 1

# Mixed precision for extra speed-up
# precision: 16

# Perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# Used to resolve a warning, no impact on logging
log_every_n_steps: 1

# Set to True to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# Enable cudnn to use the optimal set of algorithms (faster only for fixed input size)
benchmark: True

# Set the number of batches to consider for a single epoch (be careful: it applies to
# each dataloader individually)
limit_train_batches: 200
limit_val_batches: 20
limit_test_batches: 20