name: deepseg

channels:
  - conda-forge
  - pytorch
  - fvcore
  - iopath
  - defaults

dependencies:
  - nvidia::cuda-toolkit=11.8.0
  - python=3.10
  - pytorch::pytorch=2.1.0
  - torchvision=0.16.0
  - fvcore
  - iopath
  - bottler::nvidiacub
  - pytorch3d::pytorch3d=0.7.5
  - lightning=2.2.0
  - pip
  - pip:
    - webdataset==0.2.86
    - matplotlib==3.8.4
    - opencv-python==4.9.0.*
    - hydra-core==1.3.2
    - pandas==2.2.2
    - pin==2.7.0
    - imageio==2.34.0
    - timm==0.9.10
    - torchinfo==1.8.0
    - rich==13.7.1
    - scikit-image==0.24.0
    - python-libarchive==4.2.1
    - git+https://github.com/ChaoningZhang/MobileSAM.git
