_target_: models.object_segmentation_module.ObjectSegmentationLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

model:
  _target_: models.components.object_segmentation_model.ObjectSegmentationModel

  # If set to true, the model will not render the object set nor use the MobileSAM model
  use_gt_masks: true

  # Object set
  object_set_cfg:
    # Directory and name of the object set (3D models to render)
    dir: ${paths.data_dir}/google_scanned_objects
    name: gso.normalized_decimated
  
  image_size: ${data.transformations_cfg.resize}

  # Pretrained weights for the MobileSAM model
  sam_checkpoint: weights/mobile_sam.pt

  # Compile parts of the model for faster training with PyTorch 2.0
  compile: false

criterion:
  # TODO: try focal loss and dice loss
  _target_: torch.nn.BCEWithLogitsLoss
  reduction: mean
