defaults:
  - _self_
  - data: train/gso_10
  - model: train/gso
  - callbacks: default
  - logger: default
  - trainer: default
  - paths: train
  - extras: default
  - hydra: default


# Task name, determines output directory path
task_name: "train"

# If true, the model will be trained
train: True

optimized_metric: val/loss_best

# If true, the model will be evaluated on the test set
test: False

# Provide a path to a checkpoint to resume training from
# ckpt_path: logs/train/runs/2024-05-18_12-36-39*/checkpoints/epoch_492.ckpt
ckpt_path: null

# Seed for random number generators in PyTorch, numpy and python.random
seed: null
