defaults:
  - _self_
  - data: gso
  - model: default
  - callbacks: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default


# Task name, determines output directory path
task_name: "train"

# If true, the model will be trained
train: True

# Seed for random number generators in PyTorch, numpy and python.random
seed: null
