defaults:
  - _self_
  - data: gso
  - model: default
  - callbacks: null
  - logger: null
  - trainer: null
  - paths: default
  - extras: null
  - hydra: default


# Task name, determines output directory path
task_name: "train"

# If true, the model will be trained
train: True
