_target_: toolbox.evaluation.sequence_segmentation_prediction_module.SequenceSegmentationPredictionModel

probabilistic_segmentation_model:
  _target_: toolbox.modules.probabilistic_segmentation_lookup.ProbabilisticSegmentationLookup
  compile: false
  use_histograms: true
  color_space: rgb
  nb_bins: [32, 32, 32]
  output_logits: false

# Object set
object_set_cfg:
  # Directory and name of the object set (3D models to render)
  dir: ${paths.data_dir}/BCOT/models
  name: bcot

image_size: ${data.dataset.transformations_cfg.resize}

# Pretrained weights for the MobileSAM model
sam_checkpoint: weights/mobile_sam.ckpt

# Probabilistic segmentation model checkpoint
segmentation_model_checkpoint: null

# Compile parts of the model for faster training with PyTorch 2.0
compile: false

# Error metric to use to evaluate the segmentation of the sequence
error_metric:
  # Intersection over Union
  _target_: torchmetrics.JaccardIndex
  task: binary
