# _target_: toolbox.evaluation.sequence_segmentation_prediction_module.SequenceSegmentationPredictionModule

# model:
_target_: toolbox.evaluation.sequence_segmentation_prediction_module.SequenceSegmentationPredictionModel

# probabilistic_segmentation_model:
#   _target_: toolbox.modules.probabilistic_segmentation_lookup.ProbabilisticSegmentationLookup
#   compile: false
#   use_histograms: false
#   output_logits: true

probabilistic_segmentation_model:
  _target_: toolbox.modules.probabilistic_segmentation_mlp.ProbabilisticSegmentationMLP
  patch_size: 5
  compile: false
  output_logits: true

# Object set
object_set_cfg:
  # Directory and name of the object set (3D models to render)
  dir: ${paths.data_dir}/BCOT/models
  name: bcot

image_size: ${data.dataset.transformations_cfg.resize}

# Pretrained weights for the MobileSAM model
sam_checkpoint: weights/mobile_sam.ckpt

# Compile parts of the model for faster training with PyTorch 2.0
compile: false


# # criterion:
# #   _target_: torch.nn.BCEWithLogitsLoss
# #   reduction: mean

# criterion:
#   _target_: models.components.segmentation_losses.FocalDiceCombinationLoss

#   # Focal loss parameters
#   gamma: 2.0  # Focusing parameter
#   alpha: 0.25  # Balancing parameter (percentage of negative samples)

#   # Dice loss parameters
#   smooth: 1.0  # Smoothing factor

#   with_logits: true  # If 'true', sigmoid activation is applied

#   # Weights for the Focal and Dice losses
#   k_focal: 20.0
#   k_dice: 1.0
